# Generated by Django 5.0.3 on 2024-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_refrigerated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
